name: buildfork

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.2.2
        with: 
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
            CI: true
      - name: Upload code coverage
      # upload artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://screeching-car.surge.sh
    steps:
      - name: Download the Build Artifact 
        uses: actions/download-artifact@v4.1.2 
        with: 
          name: build 
      - name: deploy to surge 
        run: npx surge --project '.' --domain screeching-car.surge.sh 
        env: 
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }} 
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }} 
      
            
          
